on:
  push:
    branches:
      - main


jobs:
  terraform:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ap-south-1
      
    steps:
      - name: Checkout Terraform Code
        uses: actions/checkout@v2
        
      - name: Terraform Init
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.4.0
          
      - name: Build and Test
        run: |
          ls -al
          terraform version
          pwd
          
      - name: Terraform Validate
        run: terraform validate
        working-directory: .
        
        
      - name: Terraform Plan
        id: plan
        run: terraform plan
        working-directory: .
        
        
      - name: Terraform Apply
        run: terraform apply 
        working-directory: .
        env:
          TF_APPLY: "true"
