on:
  push:
    branches:
      - main

node-version: '16'

jobs:
  terraform:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ap-south-1
      
    steps:
      - name: Checkout Terraform Code
        uses: actions/checkout@v2
        
      - name: Terraform Init
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.4.0
      - name: Example Step
        run: |
          terraform version
          which terraform
          pwd
          ls -al
